In [1]:
import pandas as pd

In [5]:
data = pd.read_csv("movie.csv")

In [70]:
data.head()

,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Meta_score,Director,Star1,No_of_Votes,Gross
0,The Shawshank Redemption,1994,A,142,Drama,9.3,80.0,Frank Darabont,Tim Robbins,2343110,28341469.0
1,The Godfather,1972,A,175,"Crime, Drama",9.2,100.0,Francis Ford Coppola,Marlon Brando,1620367,134966411.0
2,The Dark Knight,2008,UA,152,"Action, Crime, Drama",9.0,84.0,Christopher Nolan,Christian Bale,2303232,534858444.0
3,The Godfather: Part II,1974,A,202,"Crime, Drama",9.0,90.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0
4,12 Angry Men,1957,U,96,"Crime, Drama",9.0,96.0,Sidney Lumet,Henry Fonda,689845,4360000.0

In [ ]:
data.tail()

In [10]:
data.columns

Index(['Series_Title', 'Released_Year', 'Certificate', 'Runtime', 'Genre',
       'IMDB_Rating', 'Meta_score', 'Director', 'Star1', 'No_of_Votes',
       'Gross'],
      dtype='str')

In [27]:
data.Released_Year.unique()

<ArrowStringArray>
['1994', '1972', '2008', '1974', '1957', '2003', '1993', '2010', '1999',
 '2001', '1966', '2002', '1990', '1980', '1975', '2020', '2019', '2014',
 '1998', '1997', '1995', '1991', '1977', '1962', '1954', '1946', '2011',
 '2006', '2000', '1988', '1985', '1968', '1960', '1942', '1936', '1931',
 '2018', '2017', '2016', '2012', '2009', '2007', '1984', '1981', '1979',
 '1971', '1963', '1964', '1950', '1940', '2013', '2005', '2004', '1992',
 '1987', '1986', '1983', '1976', '1973', '1965', '1959', '1958', '1952',
 '1948', '1944', '1941', '1927', '1921', '2015', '1996', '1989', '1978',
 '1961', '1955', '1953', '1925', '1924', '1982', '1967', '1951', '1949',
 '1939', '1937', '1934', '1928', '1926', '1920', '1970', '1969', '1956',
 '1947', '1945', '1930', '1938', '1935', '1933', '1932', '1922', '1943']
Length: 99, dtype: str

In [ ]:
data[data.Released_Year=="PG"]

In [26]:
data.loc[966, "Released_Year"] = "1970"

In [35]:
data[data.Released_Year=="PG"]

Empty DataFrame
Columns: [Series_Title, Released_Year, Certificate, Runtime, Genre, IMDB_Rating, Meta_score, Director, Star1, No_of_Votes, Gross]
Index: []

In [29]:
data.loc[966, "Released_Year"]

'1970'

In [33]:
data.Released_Year=data.Released_Year.astype("int")

In [ ]:
data.Certificate.unique()

In [ ]:
data.head(2)

In [ ]:
data.Runtime.unique()

In [52]:
data.Runtime=data.Runtime.str.replace(" min", "")

In [55]:
data.Runtime= data.Runtime.astype("int")

In [ ]:
data.Runtime

In [ ]:
data.columns

In [ ]:
data.info()

In [92]:
import numpy as np

df = pd.DataFrame({'nums':[1,2,np.nan,3,4,5,np.nan,7,8,9,10], 
                   'grade':['a','a','f',np.nan,'d','b','d','b','d','b','a']})
df.grade.mode()[0]

'a'

In [67]:
df.isna().sum()

nums     2
grade    1
dtype: int64

In [69]:
data.isna().sum()

Series_Title       0
Released_Year      0
Certificate      101
Runtime            0
Genre              0
IMDB_Rating        0
Meta_score       157
Director           0
Star1              0
No_of_Votes        0
Gross            169
dtype: int64

In [72]:
data.shape

(1000, 11)

In [ ]:
# data = data.dropna()
# data.dropna(inplace=True)
data.shape

In [73]:
data.shape

(1000, 11)

In [83]:
# all col with na values
data[data.isna().any(axis=1)]

,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Meta_score,Director,Star1,No_of_Votes,Gross
18,Hamilton,2020,PG-13,160,"Biography, Drama, History",8.6,90.0,Thomas Kail,Lin-Manuel Miranda,55291,NaN
20,Soorarai Pottru,2020,U,153,Drama,8.6,NaN,Sudha Kongara,Suriya,54995,NaN
30,Seppuku,1962,NaN,133,"Action, Drama, Mystery",8.6,85.0,Masaki Kobayashi,Tatsuya Nakadai,42004,NaN
32,It's a Wonderful Life,1946,PG,130,"Drama, Family, Fantasy",8.6,89.0,Frank Capra,James Stewart,405801,NaN
46,Hotaru no haka,1988,U,89,"Animation, Drama, War",8.5,94.0,Isao Takahata,Tsutomu Tatsumi,235231,NaN
...,...,...,...,...,...,...,...,...,...,...,...
993,Blowup,1966,A,111,"Drama, Mystery, Thriller",7.6,82.0,Michelangelo Antonioni,David Hemmings,56513,NaN
995,Breakfast at Tiffany's,1961,A,115,"Comedy, Drama, Romance",7.6,76.0,Blake Edwards,Audrey Hepburn,166544,NaN
996,Giant,1956,G,201,"Drama, Western",7.6,84.0,George Stevens,Elizabeth Taylor,34075,NaN
998,Lifeboat,1944,NaN,97,"Drama, War",7.6,78.0,Alfred Hitchcock,Tallulah Bankhead,26471,NaN
999,The 39 Steps,1935,NaN,86,"Crime, Mystery, Thriller",7.6,93.0,Alfred Hitchcock,Robert Donat,51853,NaN

In [ ]:
data

In [ ]:
data.dropna(subset=['Gross'], how='any')

In [ ]:
data.fillna({'Certificate':data.Certificate.mode()[0], 
             'Meta_score':data.Meta_score.mean(), 
             'Gross':data.Gross.mean()     
            } , inplace=True     
           )

In [ ]:
data.isna().sum()

In [94]:
data.Certificate.mode()[0]

'U'